<!DOCTYPE html>

<html lang="en" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:v="urn:schemas-microsoft-com:vml">
<head>
    <title></title>
    <meta content="text/html; charset=utf-8" http-equiv="Content-Type"/>
    <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
    <!--[if mso]>
    <xml>
        <o:OfficeDocumentSettings>
            <o:PixelsPerInch>96</o:PixelsPerInch>
            <o:AllowPNG/>
        </o:OfficeDocumentSettings>
    </xml><![endif]-->
</head>
<body style="background-color: #d2e7f5; margin: 0; padding: 0; -webkit-text-size-adjust: none; text-size-adjust: none;">

<p>Hi ${name},</p></br>
</br>
<p>You recently requested to reset the password for your [customer portal] account. Click the button below to proceed.</p></br>
</br>
<a href="${link}" style="text-decoration:none;display:inline-block;color:#ffffff;background-color:#03191e;border-radius:4px;width:auto;border-top:1px solid #03191E;font-weight:500;border-right:1px solid #03191E;border-bottom:1px solid #03191E;border-left:1px solid #03191E;padding-top:5px;padding-bottom:5px;font-family:Arial, Helvetica Neue, Helvetica, sans-serif;font-size:16px;text-align:center;mso-border-alt:none;word-break:keep-all;"
   target="_blank">Accept Change Password</a></br>
</br>
<p>If you did not request a password reset, please ignore this email or reply to let us know. This password reset link is only valid for the next 30 minutes.</p></br>
</br>
<p>Thanks, the AGO Social</p></br>
</body>
</html>